@startuml

!include https://raw.githubusercontent.com/vasilokb/plantUML/refs/heads/main/C4.puml

Person(user, "Пользователь", "пользователь системы фитнес-клуба")
Person(admin, "Администратор", "администратор, управляющий системой и осуществляющий поддержку пользователей")
Boundary(system, "FitLife System") {

Container(WAP, "Web applicaion", " платежей.", , , , "Java, Spring")
ContainerDb(db, "DataBase", "Хранит данные", , , , "PostgreSQL")
Rel(WAP, db, "")
Container(PaymentService, "Payment Service", "Обрабатывет платежи вот так", , , , "Node.js")
Rel(WAP, PaymentService, "Выполнение платежей")
Container(MobileApplication, "Mobile Application", "Позволяет пользователям управлять их членством", , , , "Kotlin, Swift")
Rel(MobileApplication, db, "")
}
System_Ext(api, "Third-Party API", "внешний API для интеграции данных о фитнесе", "", "\n", "\nffff")
System_Ext(bank, "Bank System", "внешняя банковская система для обработки платежей")
Rel(user, WAP, "Использует приложение")
Rel(admin, WAP, "Администрирует приложение")
Rel(WAP, api, "Потребляет фитнесс данные")
Rel(PaymentService, bank, "Выполнение платежей")

@enduml