name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'  # или можно использовать 'zulu' или 'temurin'
        java-version: '11'

    - name: Download PlantUML
      run: wget http://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

    - name: List .puml files
      run: find diagrams -name '*.puml'

    - name: Generate diagrams
      run: |
        mkdir -p output
        for file in $(find diagrams -name '*.puml'); do
          echo "Generating diagram for $file"
          java -jar plantuml.jar -tpng $file -o output
        done

    - name: List generated diagrams
      run: ls -l output

    - name: Commit and push diagrams
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add output/*
        git commit -m 'Generate PlantUML diagrams'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
