name: PlantUML Diagrams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install PlantUML
      run: sudo apt-get install -y plantuml

    - name: Generate Diagrams
      run: |
        for dir in context container component code; do
          if [ -d "diagrams/$dir" ] && [ "$(ls diagrams/$dir/*.puml 2>/dev/null)" ]; then
            echo "Generating diagrams for $dir..."
            plantuml diagrams/$dir/*.puml
          else
            echo "No .puml files found in diagrams/$dir"
          fi
        done

    - name: Commit Diagrams
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        if [ -n "$(git status --porcelain)" ]; then
          git add diagrams/**/*.png
          git commit -m "Automated diagram generation"
          git push origin main
        else
          echo "No changes to commit"
        fi
      if: success()
